### ISSUE TITLE
Printing in human-readable textual format

### ISSUE THREAD

**Issue by ubaidsk** [bwasti/wasmblr#3]
Please, could you possibly share if this library also supports emitting WebAssembly Code in `WAT` (WebAssembly Text format) format?

In case it does not support emitting in `WAT` format, could you possibly share what/where I could do some changes to get output in `WAT` format, please?

**Comment by certik** [comment]
The library is defined in https://github.com/bwasti/wasmblr/blob/b26dcd58f76f4458c3873eeaf52b4b4b0e83c7e3/wasmblr.h, and by reading through it, it seems it is generating the binary code in a straightforward manner.

I think there are other tools that can convert the binary code into a textual format, such as [wasm2wat](https://webassembly.github.io/wabt/doc/wasm2wat.1.html).

**Comment by bwasti** [comment]
@certik is right that it's only emitting binary.  I've found that you can use [wabt](https://github.com/WebAssembly/wabt) locally as well as in the browser to disassemble to WAT.
